format_version: 3
pipelines:
  gocd-pipeline:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/vivekthangathurai/SimpleGoTest
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - build-project:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            run-test:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - hello gocd
                    command: echo
                    run_if: passed
