apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-k8s-webhook-handler-
spec:
  entrypoint: ci
  onExit: exit-handler
  serviceAccountName: k8s-webhook-handler
  
  arguments:
    parameters:
      - name: image
        value: "vivek125/k8s-webhook-handler:{{workflow.annotations.k8s-webhook-handler.io/revision}}"      
  volumes:
    - name: docker-config
      configMap:
        name: docker-config     
  templates:
    - name: ci
      dag:
        tasks:
          - name: checkout
            template: checkout
          - name: build
            template: build
            arguments:
              artifacts:
              - name: source
                from: "{{dag.tasks.checkout.outputs.artifacts.source}}"
          - name: deploy
            template: deploy
            arguments:
              artifacts:
              - name: source
                from: "{{dag.tasks.checkout.outputs.artifacts.source}}"
            dependencies: [build]
    - name: checkout
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
             repo: "https://github.com/vivekthangathurai/SimpleGoTest.git"
             revision: "{{workflow.annotations.k8s-webhook-handler.io/revision}}"
      outputs:
        artifacts:
          - name: source
            path: /src
      container:
        image: golang:1.9.2
        command: ["/bin/sh", "-c"]
        args: ["cd /src && git status && ls -l"]          
            
    - name: build
      metadata:
        annotations:
          iam.amazonaws.com/role: ci-role
      inputs:
        artifacts:
          - name: source
            path: /src
      container:
        image: gcr.io/kaniko-project/executor
        args:
          - "--context=/src"
          - "--destination={{workflow.parameters.image}}"
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker/   
    - name: deploy
      inputs:
        artifacts:
          - name: source
            path: /src
      container:
        image: bitnami/kubectl:latest
        args: ["apply", "-f", "src/configmap.yaml","-n","argo"]
    - name: exit-handler
      inputs:
        artifacts:
          - name: source
            path: /src
      container:
        image: bitnami/kubectl:latest
        args: ["delete", "-f", "src/configmap.yaml","-n","argo"]    
